[package]
name = "my_rust_app"
version = "0.1.0"
edition = "2021"

# Define a binary target (this is required)
[[bin]]
name = "my_rust_app"
path = "src/main.rs"

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }