version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rust_db
      MYSQL_USER: rust_user
      MYSQL_PASSWORD: rust_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Load the SQL script
    networks:
      - rust_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  rust_app:
    build: .
    container_name: rust_container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://rust_user:rust_password@mysql:3306/rust_db
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/var/log/myapp  # Bind mount: container /var/log/myapp -> local machine ./logs
    networks:
      - rust_network

networks:
  rust_network:
    driver: bridge