version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rust_db
      MYSQL_USER: rust_user
      MYSQL_PASSWORD: rust_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # inital sql script
      - mysql_data:/var/lib/mysql  # keep MySQL data when it is restarted.
    networks:
      - rust_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  rust_app:
    build: .
    deploy:
      replicas: 3 
      restart_policy:
        condition: on-failure
      mode: replicated  
      endpoint_mode: dnsrr  # load balancing policy
    ports:
      - "3000-3002:80" 
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://rust_user:rust_password@mysql:3306/rust_db
    volumes:
      - ./logs:/var/log/myapp
    networks:
      - rust_network

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    restart: always
    depends_on:
      - rust_app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx setting file mount
    networks:
      - rust_network

networks:
  rust_network:
    driver: bridge

volumes:
  mysql_data:  # Keep MySQL data