name: Rust with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Rust Application
      run: cargo build --release

    - name: Run Rust Tests
      run: cargo test --verbose

    - name: Build Docker Image
      run: docker build -t my_rust_app .

    - name: Run Docker Container
      run: docker run --rm -d -p 3000:3000 --name rust_container my_rust_app

    - name: Check if Container is Running
      run: docker ps

    - name: Test API Endpoints
      run: |
        sleep 20  # Wait for the server to start
        curl -X POST "http://localhost:3000/user" -H "Content-Type: application/json" -d '{"id":1, "name":"Alice", "email":"alice@example.com"}'
        curl -X GET "http://localhost:3000/user/1"

    - name: Stop Container
      run: docker stop rust_container