name: Rust with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Install Rust (if not available)
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    # Run Cargo Build & Test before Dockerizing
    - name: Build Rust Application
      run: cargo build --verbose

    - name: Run Rust Tests
      run: cargo test --verbose

    # Build Docker Image
    - name: Build Docker Image
      run: docker build -t my_rust_app .

    # Run Container to Verify It Works
    - name: Run Docker Container
      run: docker run --rm -d -p 3000:3000 --name rust_container my_rust_app

    # Check if the container is running properly
    - name: Check Running Container Logs
      run: docker logs rust_container

    # Stop the container
    - name: Stop Container
      run: docker stop rust_container